### PR TITLE
Don't use Math.random() for id generation

### PR DESCRIPTION
**Pull request by isaacl**
Math.random has no guarantees of randomness.

### CODE REVIEW

**Comment by isaacl** [comment]
not sure how your builds are setup but in node crypto does have a default export... Anyway feel free to adjust or drop

**Comment by anuraaga** [comment]
@isaacl Thanks for the PR. We are following the same convention as upstream opentelemetry

https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-core/src/platform/node/RandomIdGenerator.ts

Pseudorandom is generally considered acceptable for tracing especially because the trace ID is so large. Cryptosecure random is extremely slow and puts a large burden on apps so it's generally not used in OpenTelemetry

https://github.com/open-telemetry/opentelemetry-js/issues/1334

**Comment by isaacl** [comment]
hmm well if it's a method overhead you could fill a larger buffer from crypto and slowly use it.  idk using Math.random feels vry hacky, especially the way it's done here.

**Comment by anuraaga** [comment]
I think there is overhead related to getting entropy, which could block the process especially if filling a large buffer. If you think this could be improved do you mind creating an issue at https://github.com/open-telemetry/opentelemetry-js to discuss upstream? We would want to be consistent with them.

**Pull request closed without merging**
